export const PHONEPE_CONFIG = {
  MERCHANT_ID: process.env.PHONEPE_MERCHANT_ID,
  SALT_KEY: process.env.PHONEPE_SALT_KEY,
  SALT_INDEX: process.env.PHONEPE_SALT_INDEX,
  BASE_URL: process.env.PHONEPE_BASE_URL,
  REDIRECT_URL: process.env.PHONEPE_REDIRECT_URL,
  CALLBACK_URL: process.env.PHONEPE_CALLBACK_URL,
};
